[package]
name = "motifsearch"
version = "0.1.0"
edition = "2021"
authors = ["Hyunbin Kim <khb7840@gmail.com>", "Rachel Kim <seamustard52@gmail.com>"]
description = "A bioinformatics tool for finding discontinuous motifs in protein structures"
repository = "https://github.com/steineggerlab/motifsearch"


# test optimization
[profile.test]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "motifsearch"
path = "src/cli/main.rs"

[[bin]]
name = "train"
path = "tests/train.rs"

[[bin]]
name = "vae"
path = "tests/pytorch_vae.rs"

[dependencies]
anyhow = "1.0.71"
csv = "1.2.1"
dfdx = { version = "0.11.2", features = ["numpy", "safetensors"] }
rand = "0.8.5"
tch = { version = "0.12.0", features = ["python"] }
