[package]
name = "motifsearch"
version = "0.1.0"
edition = "2021"
authors = ["Hyunbin Kim <khb7840@gmail.com>", "Rachel Kim <seamustard52@gmail.com>"]
description = "A bioinformatics tool for finding discontinuous motifs in protein structures"
repository = "https://github.com/steineggerlab/motifsearch"


# test optimization
[profile.test]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "motifsearch"
path = "src/cli/main.rs"

[[example]]
name = "data_prep"
path = "example/data_prep.rs"

[[example]]
name = "kmeans"
path = "example/kmeans.rs"

[[example]]
name = "train"
path = "example/vae_pytorch.rs"

[dependencies]
rand = "0.8.5"
pico-args = { version = "0.5.0", features = ["combined-flags"], path = "lib/pico-args" }

[dev-dependencies]
tch = { version = "0.12.0", features = ["python"] }
dfdx = { version = "0.11.2", features = ["numpy", "safetensors"] }
anyhow = { version ="1.0.71" }
csv = {version = "1.2.1"}
